### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.__version__

'2.3.5'

### <a name='1'></a> Ćwiczenie 1
Sprawdź czy wszystkie elementy tablic $A, B, C$ oraz $D$ zwracają wartość logiczną _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```



__Wskazówka:__ Użyj funkcji _np.all()._

In [3]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

In [8]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f"Wynik dla macierzy {name}: {np.all(array)}")

Wynik dla macierzy A: True
Wynik dla macierzy B: False
Wynik dla macierzy C: False
Wynik dla macierzy D: True


In [4]:
np.all(A)

np.True_

In [5]:
np.all(B)

np.False_

In [6]:
np.all(C)

np.False_

In [7]:
np.all(D)

np.True_

### <a name='2'></a> Ćwiczenie 2
Sprawdź czy wszystkie elementy tablic $A, B$ oraz $C$ zwracają wartość logiczną _True_ wzdłuż osi z indeksem 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```



__Wskazówka:__ Użyj funkcji _np.all()_ z parametrem _axis._

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [14]:
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


### <a name='3'></a> Ćwiczenie 3
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```


__Wskazówka:__ Użyj funkcji _np.any()._

In [15]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [17]:
np.any(A)

np.False_

In [16]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


### <a name='4'></a> Ćwiczenie 4
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_ wzdłuż osi z indeksem 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



__Wskazówka:__ Użyj funkcji _np.any()_ z parametrem _axis._

In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [18]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


### <a name='5'></a> Ćwiczenie 5
Sprawdź tablicę $A$ pod kątem braków danych (_np.nan_).


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


__Wskazówka:__ Użyj funkcji _np.isnan()_.

In [20]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [21]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

In [22]:
A[np.isnan(A)]

array([nan, nan])

In [26]:
A[~np.isnan(A)]

array([3., 2., 1., 5., 1., 6.])

### <a name='6'></a> Ćwiczenie 6
Utwórz tablicę zawierającą liczby od 0 do 9.

__Wskazówka:__ Użyj funkcji _np.arange()_.
```


In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### <a name='7'></a> Ćwiczenie 7
Zmień kształt tablicy jednowymiarowej na dwuwymiarową.

__Wskazówka:__ Użyj funkcji _np.reshape()_.
```

In [29]:
jednowymiarowa  = np.arange(12)

In [34]:
dwuwymiarowa = jednowymiarowa.reshape(3, 4)
dwuwymiarowa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### <a name='8'></a> Ćwiczenie 8
Wykonaj na tablicy z zadania 7 operacje wycięcia 2 wiersza.

```



In [37]:
dwuwymiarowa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
dwuwymiarowa[1,0]

np.int64(4)

In [43]:
dwuwymiarowa[1][0]

np.int64(4)

### <a name='9'></a> Ćwiczenie 9
Stwórz tablicę numpy wymiaru _4x4_ wypełnioną zerami. Ustal typ danych na _int_.

__Oczekiwany wynik:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```



__Wskazówka:__ Użyj funkcji _np.zeros()_.

In [48]:
b = np.zeros(shape=(4, 4), dtype='int')
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
b.itemsize

8

### <a name='10'></a> Ćwiczenie 10
Stwórz tablicę numpy wymiaru _10x10_ wypełnioną liczbą 255. Ustal typ danych na _float_.

__Oczekiwany wynik:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```



__Wskazówka:__ Użyj funkcji _np.ones()_ lub _np.full()_.

In [55]:
# Rozwiązanie 1
np.ones(shape=(10, 10), dtype='float') * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [54]:
# Rozwiązanie 2
np.full(shape=(10, 10), fill_value=255, dtype='float')

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])