### NumPy - biblioteka do obliczeń numerycznych

- Podstawy obliczeń numerycznych
- Porównanie szybkości z czystym Pythonem
- Kluczowe różnice pomiędzy tablicami Numpy i listami pythonowymi
- Typowe operacje na wektorach i macierzach
- Algebra liniowa

**NumPy**, czyli **Numerical Python**, to biblioteka programistyczna w języku Python, która dostarcza wsparcie dla efektywnych operacji numerycznych, zwłaszcza na dużych tablicach i macierzach danych. Jest jednym z podstawowych narzędzi w dziedzinie naukowych obliczeń i analizy danych w języku Python.

Główne cechy i funkcje biblioteki NumPy:

1. Tablice wielowymiarowe: NumPy wprowadza nowy typ danych, znany jako **"array" (tablica)**, który pozwala na przechowywanie i operowanie danymi wielowymiarowymi. Tablice w NumPy są bardziej wydajne niż standardowe listy w Pythonie i pozwalają na efektywne wykonywanie operacji matematycznych i statystycznych na danych.

2. Efektywne operacje numeryczne: NumPy dostarcza wiele wbudowanych funkcji i operacji, takich jak **dodawanie, mnożenie, podnoszenie do potęgi, funkcje trygonometryczne itp.**, które działają efektywnie na dużych zbiorach danych.

3. Indeksowanie i wycinanie: NumPy oferuje zaawansowane możliwości indeksowania i wycinania danych z tablic, co pozwala na dostęp do konkretnych elementów lub podtablic z dużą precyzją.

4. Losowanie liczb: Biblioteka umożliwia generowanie losowych liczb o różnych rozkładach, co jest przydatne w symulacjach i analizach statystycznych.

5. Integracja z innymi bibliotekami: NumPy jest często używany w połączeniu z innymi bibliotekami do naukowych obliczeń i analizy danych, takimi jak SciPy, pandas, matplotlib i scikit-learn.

6. Obsługa danych brakujących: NumPy ma wbudowane funkcje do pracy z danymi brakującymi, co jest istotne w analizie danych.

## NumPy

Dokumentacja: [https://NumPy.org/doc/](https://NumPy.org/doc/)

Biblioteka do przetwarzania numerycznego dużych wielowymiarowych tablic liczbowych. 

Typowy import:

- Strona biblioteki: https://numpy.org/
- Dokumentacja: https://numpy.org/doc/
-  ---

- Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:

```python
pip install numpy
```

In [ ]:
# !pip install numpy

In [5]:
import numpy as np
np.__version__

'2.3.5'

## `np.ndarray`


* Reprezentuje jedno lub wielowymiarową tablicę wartości. Jest to podstawowa klasa definiowana przez bibliotekę.
* Wszystkie wartości w tablicy musza być tego samego typu, czyli `np.ndarray` jest tablicą jednorodną (homogeniczną) .
* Każda wartość zajmuje tę samą określoną przez typ porcję pamięci.

## `np.array()`

Tworzy tablice z "tablicopodobnych" obiektów, np. z list:

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [8]:
sum(a)

np.int64(6)

## `dtype`

Wspólny typ dla wszystkich wartości w tablicy:

In [9]:
a.dtype

dtype('int64')

In [10]:
a = np.array([1.5, 2, 3.14])
a.dtype

dtype('float64')

In [15]:
a = np.array([1, 2, 3, 4.5])
a

array([1. , 2. , 3. , 4.5])

In [16]:
a.dtype

dtype('float64')

In [17]:
a = np.array([1, 2, 3], dtype='float64')
a

array([1., 2., 3.])

In [18]:
a = np.array([1.6, 2.1, 3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

## NumPy: typy wbudowane

Data type |Description
---|---
bool_ |Boolean (True or False) stored as a byte
int_ |Default integer type (same as C long; normally either int64 or int32)
intc |Identical to C int (normally int32 or int64)
intp |Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8 |Byte (-128 to 127)
int16 |Integer (-32768 to 32767)
int32 |Integer (-2147483648 to 2147483647)
int64 |Integer (-9223372036854775808 to 9223372036854775807)
uint8 |Unsigned integer (0 to 255)
uint16 |Unsigned integer (0 to 65535)
uint32 |Unsigned integer (0 to 4294967295)
uint64 |Unsigned integer (0 to 18446744073709551615)
float_ |Shorthand for float64.
float16 |Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 |Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 |Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ |Shorthand for complex128.
complex64 |Complex number, represented by two 32-bit floats
complex128 |Complex number, represented by two 64-bit floats