### NumPy - biblioteka do obliczeń numerycznych

- Podstawy obliczeń numerycznych
- Porównanie szybkości z czystym Pythonem
- Kluczowe różnice pomiędzy tablicami Numpy i listami pythonowymi
- Typowe operacje na wektorach i macierzach
- Algebra liniowa

**NumPy**, czyli **Numerical Python**, to biblioteka programistyczna w języku Python, która dostarcza wsparcie dla efektywnych operacji numerycznych, zwłaszcza na dużych tablicach i macierzach danych. Jest jednym z podstawowych narzędzi w dziedzinie naukowych obliczeń i analizy danych w języku Python.

Główne cechy i funkcje biblioteki NumPy:

1. Tablice wielowymiarowe: NumPy wprowadza nowy typ danych, znany jako **"array" (tablica)**, który pozwala na przechowywanie i operowanie danymi wielowymiarowymi. Tablice w NumPy są bardziej wydajne niż standardowe listy w Pythonie i pozwalają na efektywne wykonywanie operacji matematycznych i statystycznych na danych.

2. Efektywne operacje numeryczne: NumPy dostarcza wiele wbudowanych funkcji i operacji, takich jak **dodawanie, mnożenie, podnoszenie do potęgi, funkcje trygonometryczne itp.**, które działają efektywnie na dużych zbiorach danych.

3. Indeksowanie i wycinanie: NumPy oferuje zaawansowane możliwości indeksowania i wycinania danych z tablic, co pozwala na dostęp do konkretnych elementów lub podtablic z dużą precyzją.

4. Losowanie liczb: Biblioteka umożliwia generowanie losowych liczb o różnych rozkładach, co jest przydatne w symulacjach i analizach statystycznych.

5. Integracja z innymi bibliotekami: NumPy jest często używany w połączeniu z innymi bibliotekami do naukowych obliczeń i analizy danych, takimi jak SciPy, pandas, matplotlib i scikit-learn.

6. Obsługa danych brakujących: NumPy ma wbudowane funkcje do pracy z danymi brakującymi, co jest istotne w analizie danych.

## NumPy

Dokumentacja: [https://NumPy.org/doc/](https://NumPy.org/doc/)

Biblioteka do przetwarzania numerycznego dużych wielowymiarowych tablic liczbowych. 

Typowy import:

- Strona biblioteki: https://numpy.org/
- Dokumentacja: https://numpy.org/doc/
-  ---

- Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:

```python
pip install numpy
```

In [ ]:
# !pip install numpy

In [5]:
import numpy as np
np.__version__

'2.3.5'

## `np.ndarray`


* Reprezentuje jedno lub wielowymiarową tablicę wartości. Jest to podstawowa klasa definiowana przez bibliotekę.
* Wszystkie wartości w tablicy musza być tego samego typu, czyli `np.ndarray` jest tablicą jednorodną (homogeniczną) .
* Każda wartość zajmuje tę samą określoną przez typ porcję pamięci.

## `np.array()`

Tworzy tablice z "tablicopodobnych" obiektów, np. z list:

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [8]:
sum(a)

np.int64(6)

## `dtype`

Wspólny typ dla wszystkich wartości w tablicy:

In [9]:
a.dtype

dtype('int64')

In [10]:
a = np.array([1.5, 2, 3.14])
a.dtype

dtype('float64')

In [15]:
a = np.array([1, 2, 3, 4.5])
a

array([1. , 2. , 3. , 4.5])

In [16]:
a.dtype

dtype('float64')

In [17]:
a = np.array([1, 2, 3], dtype='float64')
a

array([1., 2., 3.])

In [18]:
a = np.array([1.6, 2.1, 3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

## NumPy: typy wbudowane

Data type |Description
---|---
bool_ |Boolean (True or False) stored as a byte
int_ |Default integer type (same as C long; normally either int64 or int32)
intc |Identical to C int (normally int32 or int64)
intp |Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8 |Byte (-128 to 127)
int16 |Integer (-32768 to 32767)
int32 |Integer (-2147483648 to 2147483647)
int64 |Integer (-9223372036854775808 to 9223372036854775807)
uint8 |Unsigned integer (0 to 255)
uint16 |Unsigned integer (0 to 65535)
uint32 |Unsigned integer (0 to 4294967295)
uint64 |Unsigned integer (0 to 18446744073709551615)
float_ |Shorthand for float64.
float16 |Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 |Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 |Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ |Shorthand for complex128.
complex64 |Complex number, represented by two 32-bit floats
complex128 |Complex number, represented by two 64-bit floats

## Dygresja: pamięć zajmowana przez tablicę
### `np.nbytes`

Liczba bajtów zajęta przez jedną wartość danego typu:

In [20]:
a = np.array([[1, 2, 3]])
a

array([[1, 2, 3]])

In [22]:
a.dtype

dtype('int64')

`a.itemsize` -- wspólny rozmiar w bajtach pojedynczej wartości w tablicy `a`:

In [21]:
a.itemsize

8

In [23]:
a = np.array([[1, 2], [-1.5, 3]])
a

array([[ 1. ,  2. ],
       [-1.5,  3. ]])

In [24]:
a.dtype

dtype('float64')

In [25]:
a.itemsize

8

### `.nbytes`

Liczba bajtów zajętych przez wartości tablicy:

In [28]:
a = np.array(range(10), dtype=np.int64)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a.itemsize

8

In [30]:
a.nbytes

80

 - `itemsize` zwraca rozmiar (w bajtach) jednego elementu tablicy NumPy.
 - `nbytes` zwraca całkowitą ilość pamięci (w bajtach), jaką zajmuje tablica NumPy.
 - Funkcja `sys.getsizeof()` zwraca rozmiar (w bajtach) obiektu w Pythonie, obejmujący wewnętrzne struktury pamięci obiektu. Jest używana do sprawdzenia, ile pamięci zajmuje obiekt Pythonowy, wliczając narzut związany z zarządzaniem pamięcią przez Python.

In [31]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(a.itemsize)  # Wyjście: 4 (każdy element zajmuje 4 bajty)

4


In [33]:
print(a.nbytes)  # Wyjście: 20 (5 elementów * 4 bajty na element)

20


In [35]:
import sys

sys.getsizeof(a)

132

In [37]:
print('{:<25}{:<15}{:<10}'.format('Tablica', 'Mem wartości', 'Mem obiektu'))

for k in range(6):
    a = np.array(range(k))
    print('{!r:<25}{:<15}{:<10}'.format(a, a.nbytes, sys.getsizeof(a)))

Tablica                  Mem wartości   Mem obiektu
array([], dtype=float64) 0              112       
array([0])               8              120       
array([0, 1])            16             128       
array([0, 1, 2])         24             136       
array([0, 1, 2, 3])      32             144       
array([0, 1, 2, 3, 4])   40             152       


In [38]:
lista = list(range(5))

### Poprawne porównanie rozmiarów

Aby porównać rozmiar zajmowanej pamięci przez listę i tablicę NumPy, powinniśmy użyć odpowiednich metod:
- **Dla listy**: `sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list)`
- **Dla tablicy NumPy**: `sys.getsizeof(numpy_array)` dla samego obiektu oraz `numpy_array.nbytes` dla danych.

### Wyniki i wyjaśnienie

- **Lista Pythona**:
  - `sys.getsizeof(python_list)`: rozmiar samej listy (narzut pamięciowy struktury listy).
  - `sum(sys.getsizeof(item) for item in python_list)`: rozmiar wszystkich elementów (każdy element jest oddzielnym obiektem Pythona).

- **Tablica NumPy**:
  - `sys.getsizeof(numpy_array)`: narzut obiektu tablicy NumPy.
  - `numpy_array.nbytes`: całkowity rozmiar danych przechowywanych w tablicy.

Tablica NumPy będzie zazwyczaj bardziej efektywna pamięciowo niż lista Pythona ze względu na brak dodatkowego narzutu związanego z zarządzaniem indywidualnymi obiektami elementów.

W Pythonie lista jest strukturą danych, która przechowuje referencje do obiektów, a nie same obiekty. Dlatego całkowita pamięć zajmowana przez listę obejmuje zarówno narzut związany z samą listą, jak i pamięć zajmowaną przez poszczególne elementy, do których lista odwołuje się przez referencje.

In [40]:
sys.getsizeof(lista)

104

In [41]:
sys.getsizeof(lista) + sum(sys.getsizeof(item) for item in lista)

244

In [51]:
a = np.array(range(2*10000))
a

array([    0,     1,     2, ..., 19997, 19998, 19999], shape=(20000,))

In [43]:
a.dtype

dtype('int64')

In [44]:
a.itemsize

8

In [46]:
a.nbytes

16000

In [52]:
sys.getsizeof(a)

160112

##### dla listy w Python:

In [53]:
l = []
for i in range(2*100000):
    l.append(i)

In [54]:
sys.getsizeof(l) + sum(sys.getsizeof(item) for item in l)

7224056

## Atrybuty tablic

* `.ndim` -- liczba wymiarów, liczba całkowita.
* `.shape` -- rozmiar każdego z wymiarów, krotka liczb całkowitych.
* `.size` -- całkowita liczba wartości, iloczyn wartości z krotki `.shape`.

In [59]:
a.shape

(20000,)

In [62]:
a = np.arange(-10, 10, 2)
a

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

## Tworzenie tablic z niczego

* `np.zeroes()`
* `np.ones()`
* `np.full()`
* `np.arange()`
* `np.linspace()`
* `np.random.random()`
* `np.random.normal()`
* `np.random.randint()`
* `np.eye()`
* i inne ...

In [67]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
a.shape

(3, 2)